### ISSUE TITLE
3/20 - Meeting To Do 

### ISSUE THREAD

**Issue by dusty736** [UBC-MDS/pictureperrrfect#33]
- [x] Finalize vignette

- [x] Publish package online with `pkgdown` in `usethis`

- [x] Fix up readme (Change install instructions from CRAN to GitHub?)

- [x] Initiate R package review

- [x] Initiate Python package review

**Comment by KangboLu** [comment]
looks great. let's talk about it tomorrow

**Comment by ChadNeald** [comment]
pkgdown is now published.
